import express, { json } from "express";
import "express-async-errors";
import { addtowishlist } from "./routes/addtowishlist";
import { companyprofile } from "./routes/companyprofile";
import { currentusers } from "./routes/currentuser";
import { getuserdata } from "./routes/getuserdata";
import { signin } from "./routes/signin";
import { signup } from "./routes/signup";
import { userprofile } from "./routes/userprofile";
import { verifyuser } from "./routes/verifyuser";
import { withlist } from "./routes/withlist";
import { errorhandler } from "@mspguarenteed/common";
import { NotFound } from "@mspguarenteed/common";
import dbConnection from "./config/dbConfig";
const app = express();
dbConnection();
app.use(json());
app.use(currentusers);
app.use(signup);
app.use(signin);
app.use(userprofile);
app.use(withlist);
app.use(addtowishlist);
app.use(companyprofile);
app.use(getuserdata);
app.use(verifyuser);
app.all("*", () => {
  throw new NotFound();
});
app.use(errorhandler);
export default app;
